---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/KimEungChun/argocd-practice.git
    targetRevision: main
    path: example-2
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

#    helm:
#      parameters:
#        - name: TAG
#          value: $ARGOCD_APP_REVISION
