apiVersion: v1
kind: Service
metadata:
  name: nginx-dev-service # 서비스 이름 (원하는 대로 변경 가능)
spec:
  selector:
    app: nginx          # Deployment의 Pod 템플릿 레이블과 일치해야 함 (app: nginx)
  ports:
    - protocol: TCP
      port: 80            # 서비스가 노출할 포트 (외부에서 접근할 포트)
      targetPort: 80       # 컨테이너가 실제로 리스닝하는 포트 (Deployment 컨테이너 포트와 일치)
  type: ClusterIP         # 서비스 타입 (ClusterIP: 클러스터 내부에서만 접근 가능)